export const seedProviders = [
  {
    providerId: "dr-debashis-banerjee",
    name: "Dr. Debashis Banerjee, MBBS, MD, DM",
    title: "Senior Consultant Neurologist & Headache Specialist",
    specialty: "Neurology",
    category: "neurology",
    rating: 4.92,
    reviewsCount: 184,
    experienceYears: 16,
    hospitalAffiliation: "Apollo Multispeciality Hospitals, Kolkata",
    clinicAddress: "58 Canal Circular Road, Kadapara, Salt Lake Bypass, Kolkata, WB 700054",
    city: "Kolkata",
    metroArea: "Salt Lake & EM Bypass",
    distance: "1.8 km",
    distanceKm: 1.8,
    lat: 22.5867,
    lng: 88.4086,
    consultationFee: 1200,
    insuranceAccepted: ["Star Health", "HDFC ERGO", "ICICI Lombard", "Medi Assist TPA", "Ayushman Bharat ABHA", "Care Health"],
    avatarUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=400",
    bio: "Renowned neurologist specializing in migraine pathophysiology, aura management, tension headaches, and preventative neuro-therapies across Kolkata medical institutes.",
    qualifications: "MBBS (Calcutta Medical College), MD (PGIMER), DM Neurology (NIMHANS)",
    medicalRegistrationNumber: "WBMC Reg. #58920",
    languagesSpoken: ["English", "Bengali", "Hindi"],
    nextAvailable: "Tomorrow at 10:00 AM",
    availableDays: ["2024-10-24", "2024-10-25", "2024-10-28", "2024-10-29", "2024-11-04"],
    timeSlots: ["09:00 AM", "10:00 AM", "10:45 AM", "01:30 PM", "02:45 PM", "04:00 PM"],
    telehealthAvailable: true,
    inPersonAvailable: true,
    aiMatchReason: "98% match for your recorded migraine, temple throbbing, and light sensitivity symptoms",
    phone: "+91 33 2320 3040",
    workingHours: "Mon–Sat 9:00 AM – 6:00 PM",
    facilities: ["EEG", "MRI Referral", "Telehealth", "Headache Clinic"],
  },
  {
    providerId: "medica-superspecialty-urgent",
    name: "Medica Superspecialty Hospital 24/7 Trauma Emergency",
    title: "Emergency & Acute Trauma Care Center",
    specialty: "Emergency & Urgent Care",
    category: "urgent_care",
    rating: 4.85,
    reviewsCount: 520,
    experienceYears: 24,
    hospitalAffiliation: "Medica Hospitals Group",
    clinicAddress: "127 Mukundapur, E.M. Bypass, Kolkata, West Bengal 700099",
    city: "Kolkata",
    metroArea: "Mukundapur / EM Bypass",
    distance: "2.4 km",
    distanceKm: 2.4,
    lat: 22.5134,
    lng: 88.4021,
    consultationFee: 800,
    insuranceAccepted: ["Star Health", "HDFC ERGO", "ICICI Lombard", "Medi Assist TPA", "Niva Bupa", "Ayushman Bharat (ABHA)", "Cashless TPA Desk"],
    avatarUrl: "https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&q=80&w=400",
    bio: "NABH & NABL accredited acute emergency hospital with on-site CT scan, MRI, 24/7 cardiac cath lab, rapid blood pathology, and certified emergency physicians.",
    qualifications: "NABH & NABL Accredited Level-1 Emergency & Stroke Center",
    medicalRegistrationNumber: "Govt WB Clinical Est. #CAL-2018-092",
    languagesSpoken: ["English", "Bengali", "Hindi"],
    nextAvailable: "Walk-ins Welcome • 24/7 Emergency Open",
    availableDays: ["2024-10-24", "2024-10-25", "2024-10-26", "2024-10-27"],
    timeSlots: ["Immediate Walk-in", "11:00 AM", "01:00 PM", "03:30 PM"],
    telehealthAvailable: false,
    inPersonAvailable: true,
    isUrgentFacility: true,
    emergencyWaitTime: "Approx. 10 mins",
    phone: "+91 33 6652 0000",
    workingHours: "24/7 Emergency Open",
    facilities: ["Trauma Center", "ICU", "CT/MRI", "Ambulance"],
  },
  {
    providerId: "dr-sneha-mukherjee",
    name: "Dr. Sneha Mukherjee, MBBS, MS, MRCOG",
    title: "Senior Obstetrician-Gynecologist & Reproductive Endocrinologist",
    specialty: "Obstetrics & Gynecology (OB-GYN)",
    category: "obgyn",
    rating: 4.96,
    reviewsCount: 240,
    experienceYears: 15,
    hospitalAffiliation: "AMRI Hospitals Dhakuria & Fortis Anandapur",
    clinicAddress: "Block A, Scheme LII, Southern Avenue / Dhakuria, Kolkata, WB 700029",
    city: "Kolkata",
    metroArea: "Dhakuria & Southern Avenue",
    distance: "3.2 km",
    distanceKm: 3.2,
    lat: 22.5123,
    lng: 88.3678,
    consultationFee: 1000,
    insuranceAccepted: ["Star Health", "HDFC ERGO", "Care Health", "ICICI Lombard", "Medi Assist"],
    avatarUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400",
    bio: "Distinguished gynaecologist specializing in menstrual cycle irregularities, PCOS/PCOD reversal, fertility tracking, endometriosis, and reproductive hormone balance.",
    qualifications: "MBBS (RG Kar Medical College), MS OB-GYN, MRCOG (London, UK)",
    medicalRegistrationNumber: "WBMC Reg. #64312",
    languagesSpoken: ["English", "Bengali", "Hindi"],
    nextAvailable: "Friday at 11:00 AM",
    availableDays: ["2024-10-25", "2024-10-28", "2024-10-30", "2024-11-01"],
    timeSlots: ["09:00 AM", "10:15 AM", "11:00 AM", "01:30 PM", "03:15 PM"],
    telehealthAvailable: true,
    inPersonAvailable: true,
    aiMatchReason: "Expert companion for your cycle tracking & luteal phase symptom logs",
    phone: "+91 33 6626 0000",
    workingHours: "Mon–Sat 10:00 AM – 5:00 PM",
    facilities: ["Ultrasound", "Fertility Counseling", "Telehealth", "PCOS Clinic"],
  },
  {
    providerId: "dr-amitava-roy",
    name: "Dr. Amitava Roy, MBBS, MD, FCCP",
    title: "Consultant Physician & Family Medicine Specialist",
    specialty: "General Practice & Internal Medicine",
    category: "general",
    rating: 4.88,
    reviewsCount: 142,
    experienceYears: 18,
    hospitalAffiliation: "Belle Vue Clinic & Woodlands Multispeciality Hospital",
    clinicAddress: "9 Dr. U. N. Brahmachari Street, Park Street Area, Kolkata, WB 700017",
    city: "Kolkata",
    metroArea: "Park Street & Loudon Street",
    distance: "4.1 km",
    distanceKm: 4.1,
    lat: 22.5512,
    lng: 88.3534,
    consultationFee: 800,
    insuranceAccepted: ["Star Health", "National Insurance", "HDFC ERGO", "Bajaj Allianz", "Medi Assist TPA"],
    avatarUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400",
    bio: "Dedicated senior physician focusing on comprehensive preventive checkups, seasonal infections, hypertension, diabetes management, and holistic lifestyle medicine.",
    qualifications: "MBBS (IPGMER SSKM Kolkata), MD General Medicine (AIIMS New Delhi)",
    medicalRegistrationNumber: "WBMC Reg. #51204",
    languagesSpoken: ["English", "Bengali", "Hindi"],
    nextAvailable: "Thursday at 02:30 PM",
    availableDays: ["2024-10-24", "2024-10-25", "2024-10-29", "2024-10-30"],
    timeSlots: ["09:30 AM", "11:15 AM", "02:30 PM", "03:45 PM", "05:00 PM"],
    telehealthAvailable: true,
    inPersonAvailable: true,
    aiMatchReason: "Optimal for annual wellness checkups & ongoing primary care in central Kolkata",
    phone: "+91 33 2287 2321",
    workingHours: "Mon–Fri 9:00 AM – 7:00 PM",
    facilities: ["Preventive Care", "Diabetes Clinic", "Telehealth"],
  },
  {
    providerId: "dr-rajiv-mehta",
    name: "Dr. Rajiv Mehta, MBBS, MD, DM, FACC",
    title: "Senior Interventional Cardiologist & Cardiovascular Prevention Specialist",
    specialty: "Cardiology",
    category: "cardiology",
    rating: 4.94,
    reviewsCount: 210,
    experienceYears: 20,
    hospitalAffiliation: "Fortis Hospital Anandapur & BM Birla Heart Research Centre",
    clinicAddress: "730 Anandapur, E.M. Bypass Road, Kolkata, West Bengal 700107",
    city: "Kolkata",
    metroArea: "Anandapur / EM Bypass",
    distance: "4.8 km",
    distanceKm: 4.8,
    lat: 22.5156,
    lng: 88.4023,
    consultationFee: 1500,
    insuranceAccepted: ["Star Health", "HDFC ERGO", "ICICI Lombard", "Care Health", "Niva Bupa", "Medi Assist"],
    avatarUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400",
    bio: "Cardiologist leading preventive cardiac evaluations, hypertension optimization, echocardiography, rhythm diagnostics, and heart-healthy lifestyle therapies.",
    qualifications: "MBBS, MD, DM Cardiology (AIIMS), Fellow American College of Cardiology",
    medicalRegistrationNumber: "WBMC Reg. #49811",
    languagesSpoken: ["English", "Bengali", "Hindi", "Gujarati"],
    nextAvailable: "Friday at 01:15 PM",
    availableDays: ["2024-10-25", "2024-10-29", "2024-10-31", "2024-11-05"],
    timeSlots: ["10:00 AM", "11:15 AM", "01:15 PM", "02:30 PM", "04:15 PM"],
    telehealthAvailable: true,
    inPersonAvailable: true,
    aiMatchReason: "Recommended for resting heart rate & blood pressure optimization",
    phone: "+91 33 6628 7777",
    workingHours: "Mon–Sat 10:00 AM – 6:00 PM",
    facilities: ["Echo", "Stress Test", "Cardiac Rehab", "Telehealth"],
  },
  {
    providerId: "dr-priya-sen",
    name: "Dr. Priya Sen, MBBS, MD (DVL)",
    title: "Senior Consultant Dermatologist & Cosmetologist",
    specialty: "Dermatology & Skin Wellness",
    category: "dermatology",
    rating: 4.9,
    reviewsCount: 168,
    experienceYears: 12,
    hospitalAffiliation: "Woodlands Multispeciality Hospital, Alipore",
    clinicAddress: "8/5 Alipore Road, Alipore, Kolkata, West Bengal 700027",
    city: "Kolkata",
    metroArea: "Alipore & New Alipore",
    distance: "5.5 km",
    distanceKm: 5.5,
    lat: 22.5245,
    lng: 88.3312,
    consultationFee: 900,
    insuranceAccepted: ["Star Health", "HDFC ERGO", "Care Health", "Medi Assist TPA"],
    avatarUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=400",
    bio: "Specialist in hormonal acne, inflammatory scalp conditions, pigmentary disorders, allergy dermoscopy, and personalized dermatological skincare protocols.",
    qualifications: "MBBS, MD Dermatology (Calcutta School of Tropical Medicine)",
    medicalRegistrationNumber: "WBMC Reg. #71045",
    languagesSpoken: ["English", "Bengali", "Hindi"],
    nextAvailable: "Next Monday at 09:30 AM",
    availableDays: ["2024-10-28", "2024-10-29", "2024-10-30"],
    timeSlots: ["09:30 AM", "11:00 AM", "02:00 PM", "03:30 PM"],
    telehealthAvailable: true,
    inPersonAvailable: true,
    aiMatchReason: "Matches skin wellness logging & hormonal acne evaluations",
    phone: "+91 33 2479 5131",
    workingHours: "Mon–Sat 10:00 AM – 5:00 PM",
    facilities: ["Dermoscopy", "Acne Clinic", "Telehealth"],
  },
];
